// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type Negotiation struct {
	ID    string  `json:"id"`
	Note  *string `json:"note"`
	Done  bool    `json:"done"`
	Quest *Quest  `json:"quest"`
}

type NewNegotiation struct {
	QuestID string  `json:"questId"`
	Note    *string `json:"note"`
	Done    bool    `json:"done"`
}

type NewQuest struct {
	Title     string  `json:"title"`
	Text      string  `json:"text"`
	Reward    string  `json:"reward"`
	Incentive *string `json:"incentive"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type Quest struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Text      string  `json:"text"`
	Reward    string  `json:"reward"`
	Incentive *string `json:"incentive"`
}
