// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewQuest struct {
	Title     string  `json:"title"`
	Text      string  `json:"text"`
	Reward    string  `json:"reward"`
	Incentive *string `json:"incentive"`
}

type Quest struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Text      string  `json:"text"`
	Reward    string  `json:"reward"`
	Incentive *string `json:"incentive"`
}
